#!/bin/bash
# Brings selected workspace to the current output
# Should be used with menu-workspaces and only for currently occupied workspaces
# Free workspaces can be bringed to the current output with mod+<workspace number>

workspace=$(menu-workspaces)
echo "Bringing $workspace to $current_output"

i3-msg "[workspace=${workspace}]" move workspace to output current
