#!/bin/bash

if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc
dmenu_cmd="dmenu $DMENU_OPTIONS"

declare -A radio_stations

radio_stations[0 TURN OFF]=""
radio_stations[SEARCH YOUTUBE]=""
radio_stations[Radio Pielgrzym - pieśni]="http://shoutcast.com.pl:9444/"
radio_stations[Radio Pielgrzym - kazania i reportaże]="http://shoutcast.com.pl:9448/"
radio_stations[Radio Pielgrzym - kazania]="http://shoutcast.com.pl:9450/"
radio_stations[CodeRadio]="https://coderadio-admin-v2.freecodecamp.org/listen/coderadio/radio.mp3"
radio_stations[HPR1 Traditional Classic Country]="https://us2.maindigitalstream.com/ssl/7713"
radio_stations[HPR2 Todays Classic Country]="https://us2.maindigitalstream.com/ssl/7735"
radio_stations[HPR4 Gospel Bluegrass]="https://us2.maindigitalstream.com/ssl/7739"
radio_stations[Chillstep.info]="https://chillstep.info/radio/stream.ogg?1696871921731"
radio_stations[10 Hours of Messianic Jewish Worship Music]="https://www.youtube.com/watch?v=fnuYjtMH-NA"
radio_stations[Lofi Girl]="https://www.youtube.com/watch?v=jfKfPfyJRdk"
radio_stations[Synthwave Boy]="https://www.youtube.com/watch?v=4xDzrJKXOOY"
radio_stations[Classical Piano]="https://www.youtube.com/watch?v=tSlOlKRuudU"
radio_stations[Productivity Music | ADHD Relief Music]="https://www.youtube.com/watch?v=7pDy0K1h8cw"

chosen=$(printf '%s\n' "${!radio_stations[@]}" | sort -n | $dmenu_cmd -i -l 20 -p "Radio:")

if [[ "$chosen" == "quit" ]]; then
        echo "Program terminated" && exit 1

elif [[ "$chosen" == "TURN OFF" ]]; then
        echo "Turning radio down..."
        pkill mpv;

elif [[ "$chosen" == "SEARCH YOUTUBE" ]]; then
        echo "Starting ytfzf..."
        pkill mpv;
        ytfzf -D --detach --url-handler-opts='--no-video';
        retVal=$?
        if [ $retVal -eq 4 ]; then
                notify-send "ytfzf (dmenu-radio): No results scraped"
        fi
        exit $retVal

elif [ "$chosen" ]; then
        echo "Turning radio $chosed..."
        pkill mpv;
        mpv --no-video ${radio_stations[$chosen]};

else
        echo "Program terminated" && exit 1
fi
