#!/bin/bash

if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc
dmenu_cmd="dmenu $DMENU_OPTIONS"

HAML_CONFIGURATION_REPO="$HOME/Work/Onwelo/repos/haml-configuration"

declare -a options=(
"dev compose - $HAML_CONFIGURATION_REPO/dev/docker-compose.yml"
"dev .env"
"dev secrets"
"prod compose - $HAML_CONFIGURATION_REPO/prod/docker-compose.yml"
"prod .env"
"prod secrets"
"quit"
)

chosen=$(printf '%s\n' "${options[@]}" | $dmenu_cmd -i -l 20 -p "Open config")

if [[ "$chosen" == "quit" ]]; then
        echo "Program terminated" && exit 1

elif [ "$chosen" == "dev .env" ]; then
        $TERM -e sops --input-type dotenv --output-type dotenv $HAML_CONFIGURATION_REPO/dev/.env.enc

elif [ "$chosen" == "prod .env" ]; then
        $TERM -e sops --input-type dotenv --output-type dotenv $HAML_CONFIGURATION_REPO/prod/.env.enc

elif [ "$chosen" == "dev secrets "]; then
        dmenu-haml-secrets dev
        exit 0

elif [ "$chosen" == "prod secrets "]; then
        dmenu-haml-secrets prod
        exit 0

elif [ "$chosen" ]; then
        filename=$(printf '%s\n' "${chosen}" | awk '{print $NF}')
        $TERM -e nvim $filename;

else
        echo "Program terminated" && exit 1
fi
