#!/bin/bash

# check if idasen is installed
if ! [ -x "$(command -v idasen)" ]; then
        echo "Error: idasen is not installed." && exit 1
fi

# use custom dmenu config if it exists
if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc
dmenu_cmd="dmenu $DMENU_OPTIONS"

# load predefined positions from idasen.yaml to 'options' array
declare -a options=()
while read line; do
        options+=("${line}m");
done < <(tail -n +3 ~/.config/idasen/idasen.yaml)

# let user pick next position
chosen=$(printf '%s\n' "${options[@]}" | $dmenu_cmd -i -l 20 -p "Pick Idasen position:")

# change position if any was chosen and set timer for next position change
if [ "$chosen" ]; then
        position_name=$(printf '%s\n' "${chosen}" | sed s/://g | awk '{print $1}')
        notify-send "Idasen" "Setting Idasen desk to position: $position_name..." -t 5000 
        idasen $position_name && sleep 1800 && notify-send "Idasen" "It's time to change position!" --action 'change position' -t 600000 | grep "0" && dmenu-idasen &
else
        echo "Program terminated" && exit 1
fi
