#!/bin/bash

if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc
dmenu_cmd="dmenu $DMENU_OPTIONS"

declare -a options=`cat ~/.local/share/emoji`

chosen=$(printf '%s\n' "${options[@]}" | $dmenu_cmd -i -l 20 -p "Pick emoji:")

if [ "$chosen" ]; then
        echo $chosen | awk '{print $1;}' | xclip -sel clip
else
        echo "Program terminated" && exit 1
fi
