#!/bin/bash
# Use menu to show a menu of config files and open selected in editor

declare -a options=(
"kitty - $HOME/.config/kitty/kitty.conf"
"alacritty - $HOME/.config/alacritty/alacritty.yml"
"i3 - $HOME/.config/i3/config"
"i3blocks - $HOME/.config/i3blocks/config"
"newsboat URLs - $HOME/.config/newsboat/urls"
"newsboat - $HOME/.config/newsboat/config"
"neovim - $HOME/.config/nvim/init.lua"
"picom - $HOME/.config/i3/picom.conf"
"quit"
)

chosen=$(printf '%s\n' "${options[@]}" | menu -i -l 20 -p "Open config")


if [[ "$chosen" == "quit" ]]; then
        echo "Program terminated" && exit 1

elif [ "$chosen" ]; then
        filename=$(printf '%s\n' "${chosen}" | awk '{print $NF}')
        $TERMINAL_CMD -e nvim $filename
else
        echo "Program terminated" && exit 1
fi
