#!/bin/bash
# DEPRECATED!!!
# I use menu-browser instead because I have different browsers for personal/work purposes now

declare -a options=(
"Private: Default"
"Ari10: Profile 1"
)

chosen=$(printf '%s\n' "${options[@]}" | menu -i -l 20 -p "Brave:")

if [ "$chosen" ]; then
        # take everything after the colon
        option=$(printf '%s\n' "${chosen}" | awk '{split($0,a,": "); print a[2]}')
        echo $option
        brave --profile-directory="$option" $@
else
        echo "Program terminated" && exit 1
fi
