#!/bin/bash

# Inspired by Luke Smith's 'ducksearch' script.
# Without input will open Google.
# URLs will be directly handed to the browser.
# Anything else will be search for via Google.

pgrep -x menu && exit

choice=$(echo "" | menu -i -p "Search Google:") || exit 1

if [ "$choice" = ""  ]; then
    $BROWSER "https://google.com"
else
    # Detect if url
    if [[ "$choice" =~ ^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$ ]]; then
        $BROWSER "$choice"
    else
        $BROWSER "https://google.com/search?q=$choice"
    fi
fi
