#!/bin/bash

declare -a profiles=(
        "Brave"
        "Google Chrome (Ari10)"
        "Chromium"
        "Firefox"
        "Qutebrowser"
)

declare -a options=(
"Main page"
"New meeting"
"Join a meeting (from clipboard)"
)

# Pick Brave Profile
profile=$(printf '%s\n' "${profiles[@]}" | menu -i -l 20 -p "Pick Brave profile:")
if [ "$profile" == "Brave" ]; then
        browser="brave"
elif [ "$profile" == "Google Chrome (Ari10)" ]; then
        browser="google-chrome-stable"
elif [ "$profile" == "Chromium" ]; then
        browser="chromium"
elif [ "$profile" == "Firefox" ]; then
        browser="firefox"
elif [ "$profile" == "Qutebrowser" ]; then
        browser="qutebrowser"
else
        echo "Program terminated" && exit 1
fi

# Pick Google Meet option
chosen=$(printf '%s\n' "${options[@]}" | menu -i -l 20 -p "Pick Google Meet option:")
if [ "$chosen" == "Main page" ]; then
        link="https://meet.google.com/"
elif [ "$chosen" == "New meeting" ]; then
        link="https://meet.google.com/new"
elif [ "$chosen" == "Join a meeting (from clipboard)" ]; then
        # get link from clipboard
        echo "Getting link from clipboard..."
        link=`xclip -o`
        echo $link
        if [ "$link" ]; then
                echo "Opening Google Meet meeting $link..."
        else
                echo "Program terminated - no link in clipboard" && exit 1
        fi
else
        echo "Program terminated" && exit 1
fi

$browser --app="$link"
