#!/bin/bash

# Opens a dropdown terminal in i3, or toggles it if already open.
# $1 is the option to pass to the terminal.
# The option might be one of the following:
# - terminal
# - files
# - news
# - notes
# - gtd
# - python
# - translator
# - mixer
# - any other command to be executed in a terminal
#
# The script uses terminal class to determine if the window is already open.
# It names the window with the class name, so that it can be easily identified.
# The class name is "dropdown" + the option name.

[ -z "$1" ] && exit

class=dropdown$1
spawn_kitty="exec --no-startup-id kitty -T $class --class $class $(echo '$@' | cut -d ' ' -f2-) -e"

if [ -z `xwininfo -tree -root | grep "\"$class\""`]; then
	echo "Window not detected... spawning.";

	case "$1" in
		files) i3 "$spawn_kitty yazi";;
		gtd) i3 "$spawn_kitty bash -c 'cd $HOME/notes && vim gtd.md'";;
		mixer) i3 "$spawn_kitty ncpamixer";;
		news) i3 "$spawn_kitty newsboat";;
		notes) i3 "$spawn_kitty bash -c 'cd $HOME/notes && vim -c :VimwikiIndex'";;
		python) i3 "$spawn_kitty ipython --no-banner";;
		terminal) i3 "$spawn_kitty tmux";;
		translator) i3 "$spawn_kitty gtt";;
		*) i3 "$spawn_kitty $1";;
	esac
fi

until xwininfo -tree -root | grep "\"$class\""; do
	echo "Waiting for window to be open..."
	sleep 0.1
done

i3 "[instance=\"$class\"] scratchpad show, move position center; [instance=\"$class\"]"
