#!/bin/bash

# Toggle floating dropdown terminal in i3, or start if non-existing.
# $1 is	the script run in the terminal.
# All other args are terminal settings.
# Terminal names are in dropdown_* to allow easily setting i3 settings.

[ -z "$1" ] && exit

if [ -z `xwininfo -tree -root | grep "\"$1\""`]; then
	echo "Window not detected... spawning.";

	case "$1" in
		dropdownpavucontrol) i3 "exec --no-startup-id pavucontrol --class $1";;
		dropdownbluetooth) i3 "exec --no-startup-id blueman-manager --class $1";;
		dropdownnotes|dropdowngtd|dropdownnewsboat) i3 "exec --no-startup-id kitty -T $1 --class $1 $(echo '$@' | cut -d ' ' -f2-) -c ~/.config/kitty/kitty.notes.conf -e ~/.config/i3/scripts/$1";;
		*) i3 "exec --no-startup-id kitty -T $1 --class $1 $(echo '$@' | cut -d ' ' -f2-) -e ~/.config/i3/scripts/$1";;
	esac
fi

until xwininfo -tree -root | grep "\"$1\""; do
	echo "Waiting for window to be open..."
	sleep 0.1
done

i3 "[instance=\"$1\"] scratchpad show, move position center; [instance=\"$1\"]";
