#!/bin/bash
# Toggle VPN connection between on and off
# This script needs networkmanager and variable DEFAULT_VPN to be set
# Author: Norbert Chmiel
# License: MIT
if [[ -z $DEFAULT_VPN ]]; then
	echo "DEFAULT_VPN not set, exiting...";
	exit 1
fi

if [[ -n $(nmcli con | grep -i vpn | awk '{if ($4 != "--") print $4}') ]]; then
	echo "Disconnecting VPN $DEFAULT_VPN"
	nmcli connection down $DEFAULT_VPN
else
	echo "Connecting VPN $DEFAULT_VPN"
	nmcli connection up $DEFAULT_VPN
fi
