#!/bin/bash
rsync -aAXHv --delete --exclude={"*/.cache","*/Cache/","*/Cache*","*/cache*","*/Onwelo","*/onwelo"} /home/norbert rsync://Norbert@192.168.0.106:873/precel/home_backup
notify-send "Backup - Home directory" "Home directory backup finished"
