#!/bin/bash

if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc
dmenu_cmd="dmenu $DMENU_OPTIONS"

declare -a options=(
"O'Reilly - https://learning.oreilly.com/"
"quit"
)

chosen=$(printf '%s\n' "${options[@]}" | $dmenu_cmd -i -l 20 -p "Brave app:")

if [[ "$chosen" == "quit" ]]; then
        echo "Program terminated" && exit 1

elif [ "$chosen" ]; then
        appname=$(printf '%s\n' "${chosen}" | awk '{print $1}')
        url=$(printf '%s\n' "${chosen}" | awk '{print $NF}')
        echo "Opening $appname..."
        brave --app=$url

else
        echo "Program terminated" && exit 1
fi
