#!/bin/bash

if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc
dmenu_cmd="dmenu $DMENU_OPTIONS"


declare -a options=(
`xrandr | grep " connected" | awk '{ print $1 } '`
"quit"
)

chosen=$(printf '%s\n' "${options[@]}" | $dmenu_cmd -l 10 -p "Pick monitor for Wacom stylus:")

if [[ "$chosen" == "quit" ]]; then
        echo "Program terminated" && exit 1

elif [ "$chosen" ]; then
        stylus_id=`xinput | grep stylus | awk '{ print $8 }' | sed 's/id=//g'`
        echo "Setting input $stylus_id to screen $chosen..."
        xinput map-to-output $stylus_id $chosen

else
        echo "Program terminated" && exit 1
fi
