#!/bin/bash

if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc
dmenu_cmd="dmenu $DMENU_OPTIONS"

declare -a options=(
"Turn Off"
"Radio Pielgrzym - pieśni - http://shoutcast.com.pl:9444/"
"Radio Pielgrzym - kazania i reportaże - http://shoutcast.com.pl:9448/"
"Radio Pielgrzym - kazania - http://shoutcast.com.pl:9450/"
"CodeRadio - https://coderadio-relay-nyc.freecodecamp.org/radio/8010/radio.mp3"
"LoFi on Zeno.fm - https://stream-160.zeno.fm/0r0xa792kwzuv?zs=9qkW01L6QU66RZF0Y4RO6Q"
"Bluegrass Gospel Radio on Zeno.fm - https://stream-153.zeno.fm/uv9m03e8h0hvv?zs=pgx81fu9QNaoJ9I9pEME4w"
"HPR1 Traditional Classic Country - https://us2.maindigitalstream.com/ssl/7713"
"HPR4 Gospel Bluegrass - https://us2.maindigitalstream.com/ssl/7739"
"quit"
)

chosen=$(printf '%s\n' "${options[@]}" | $dmenu_cmd -i -l 20 -p "Radio:")

if [[ "$chosen" == "quit" ]]; then
        echo "Program terminated" && exit 1

elif [[ "$chosen" == "Turn Off" ]]; then
        echo "Turning radio down..."
        pkill mplayer;

elif [ "$chosen" ]; then
        radioname=$(printf '%s\n' "${chosen}" | awk '{print $1}')
        radiourl=$(printf '%s\n' "${chosen}" | awk '{print $NF}')
        echo "Turning radio $radioname..."
        pkill mplayer;
        mplayer -nocache -afm ffmpeg $radiourl;

else
        echo "Program terminated" && exit 1
fi
