#!/bin/bash

if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc
dmenu_cmd="dmenu $DMENU_OPTIONS"

declare -A radio_stations

radio_stations[Turn Off]=""
radio_stations[Radio Pielgrzym - pieśni]="http://shoutcast.com.pl:9444/"
radio_stations[Radio Pielgrzym - kazania i reportaże]="http://shoutcast.com.pl:9448/"
radio_stations[Radio Pielgrzym - kazania]="http://shoutcast.com.pl:9450/"
radio_stations[CodeRadio]="https://coderadio-admin-v2.freecodecamp.org/listen/coderadio/radio.mp3"
radio_stations[LoFi on Zeno.fm]="https://stream-160.zeno.fm/0r0xa792kwzuv?zs=9qkW01L6QU66RZF0Y4RO6Q"
radio_stations[Bluegrass Gospel Radio on Zeno.fm]="https://stream-153.zeno.fm/uv9m03e8h0hvv?zs=pgx81fu9QNaoJ9I9pEME"
radio_stations[HPR1 Traditional Classic Country]="https://us2.maindigitalstream.com/ssl/7713"
radio_stations[HPR4 Gospel Bluegrass]="https://us2.maindigitalstream.com/ssl/7739"
radio_stations[Chillstep.info]="https://chillstep.info/radio/stream.ogg?1696871921731"

chosen=$(printf '%s\n' "${!radio_stations[@]}" | sort -n | $dmenu_cmd -i -l 20 -p "Radio:")

if [[ "$chosen" == "quit" ]]; then
        echo "Program terminated" && exit 1

elif [[ "$chosen" == "Turn Off" ]]; then
        echo "Turning radio down..."
        pkill mplayer;

elif [ "$chosen" ]; then
        echo "Turning radio $chosed..."
        pkill mplayer;
        mplayer ${radio_stations[$chosen]};

else
        echo "Program terminated" && exit 1
fi
