#!/bin/bash

declare -a options=(
"Main page"
"New meeting"
"Join a meeting (from clipboard)"
)

# Pick Google Meet option
chosen=$(printf '%s\n' "${options[@]}" | menu -i -l 20 -p "Pick Google Meet option:")
if [ "$chosen" == "Main page" ]; then
        link="https://meet.google.com/"
elif [ "$chosen" == "New meeting" ]; then
        link="https://meet.google.com/new"
elif [ "$chosen" == "Join a meeting (from clipboard)" ]; then
        # get link from clipboard
        echo "Getting link from clipboard..."
        link=`clippaste`
        echo $link
        if [ "$link" ]; then
                echo "Opening Google Meet meeting $link..."
        else
                echo "Program terminated - no link in clipboard" && exit 1
        fi
else
        echo "Program terminated" && exit 1
fi

brave --app="$link"
