#!/bin/bash

declare -A radio_stations

radio_stations[0 TURN OFF]=""
radio_stations[SEARCH YOUTUBE]=""
radio_stations[Radio Pielgrzym - pieśni]="http://shoutcast.com.pl:9444/"
radio_stations[Radio Pielgrzym - kazania i reportaże]="http://shoutcast.com.pl:9448/"
radio_stations[Radio Pielgrzym - kazania]="http://shoutcast.com.pl:9450/"
radio_stations[CodeRadio]="https://coderadio-admin-v2.freecodecamp.org/listen/coderadio/radio.mp3"
radio_stations[HPR1 Traditional Classic Country]="https://us2.maindigitalstream.com/ssl/7713"
radio_stations[HPR2 Todays Classic Country]="https://us2.maindigitalstream.com/ssl/7735"
radio_stations[HPR4 Gospel Bluegrass]="https://us2.maindigitalstream.com/ssl/7739"
radio_stations[Chillstep.info]="https://chillstep.info/radio/stream.ogg?1696871921731"
radio_stations[10 Hours of Messianic Jewish Worship Music]="https://www.youtube.com/watch?v=fnuYjtMH-NA"
radio_stations[Lofi Girl]="https://www.youtube.com/watch?v=jfKfPfyJRdk"
radio_stations[Synthwave Boy]="https://www.youtube.com/watch?v=4xDzrJKXOOY"
radio_stations[Classical Piano]="https://www.youtube.com/watch?v=tSlOlKRuudU"
radio_stations[Productivity Music | ADHD Relief Music]="https://www.youtube.com/watch?v=RG2IK8oRZNA"

chosen=$(printf '%s\n' "${!radio_stations[@]}" | sort -n | menu -i -l 20 -p "Radio:")

if [[ "$chosen" == "quit" ]]; then
        echo "Program terminated" && exit 1

elif [[ "$chosen" == "0 TURN OFF" ]]; then
        echo "Turning radio down..."
        pkill mpv;

elif [[ "$chosen" == "SEARCH YOUTUBE" ]]; then
        echo "Starting ytfzf..."
        ytfzf -D --detach --url-handler-opts='--no-video';
        retVal=$?
        if [ $retVal -eq 4 ]; then
                notify-send "ytfzf (menu-radio): No results scraped"
        elif [ $retVal -eq 0]; then
                pkill mpv;
        fi
        exit $retVal

elif [[ "${radio_stations[$chosen]}" != "" ]]; then
        echo "Turning radio $chosed..."
        pkill mpv;
        mpv --no-video ${radio_stations[$chosen]};

elif [[ "$chosen" != "" ]]; then
        echo "Starting ytfzf..."
        ytfzf -D --detach --url-handler-opts='--no-video' $chosen;
        retVal=$?
        if [ $retVal -eq 4 ]; then
                notify-send "ytfzf (menu-radio): No results scraped"
        elif [ $retVal -eq 0]; then
                pkill mpv;
        fi
        exit $retVal

else
        echo "Program terminated" && exit 1
fi
