#!/bin/bash

declare -A radio_stations

radio_stations[0 TURN OFF]=""
radio_stations[SEARCH YOUTUBE]=""
radio_stations[BrainFM]=""
radio_stations[Radio Pielgrzym - pieśni]="http://shoutcast.com.pl:9444/"
radio_stations[Radio Pielgrzym - kazania i reportaże]="http://shoutcast.com.pl:9448/"
radio_stations[Radio Pielgrzym - kazania]="http://shoutcast.com.pl:9450/"
radio_stations[CodeRadio]="https://coderadio-admin-v2.freecodecamp.org/listen/coderadio/radio.mp3"
radio_stations[HPR1 Traditional Classic Country]="https://us2.maindigitalstream.com/ssl/7713"
radio_stations[HPR2 Todays Classic Country]="https://us2.maindigitalstream.com/ssl/7735"
radio_stations[HPR4 Gospel Bluegrass]="https://us2.maindigitalstream.com/ssl/7739"
radio_stations[Lofi Girl]="https://www.youtube.com/watch?v=jfKfPfyJRdk"
radio_stations[Synthwave Boy]="https://www.youtube.com/watch?v=4xDzrJKXOOY"
radio_stations[Classical Piano]="https://www.youtube.com/watch?v=tSlOlKRuudU"
radio_stations[Productivity Music | ADHD Relief Music]="https://www.youtube.com/watch?v=RG2IK8oRZNA"
radio_stations[Christian LoFi]="https://www.youtube.com/watch?v=qXPoj_VYb3U"
radio_stations[JimTV [shuffled]]="https://www.youtube.com/playlist?list=PLZGcQAxf5NjPjWQvlFkOeK7EdYtxeCf4r"

chosen=$(printf '%s\n' "${!radio_stations[@]}" | sort -n | menu -i -l 20 -p "Radio:")

if [[ "$chosen" == "quit" ]]; then
        echo "Program terminated" && exit 1

elif [[ "$chosen" == "0 TURN OFF" ]]; then
        echo "Turning radio down..."
        pkill mpv;

elif [[ "$chosen" == "SEARCH YOUTUBE" ]]; then
        notify-send "Searching YouTube is disabled for ytfzf does not work and I wait for alternative..."
        # echo "Starting ytfzf..."
        # ytfzf -D --detach --url-handler-opts='--no-video';
        # retVal=$?
        # if [ $retVal -eq 4 ]; then
        #         notify-send "ytfzf (menu-radio): No results scraped"
        # elif [ $retVal -eq 0]; then
        #         pkill mpv;
        # fi
        # exit $retVal

elif [[ "$chosen" == "BrainFM" ]]; then
        notify-send "Starting BrainFM in browser app mode..."
        $BROWSER --app=https://my.brain.fm/

elif [[ "${radio_stations[$chosen]}" != "" ]]; then
        echo "Turning radio $chosen..."
        pkill mpv;
        if [[ "$chosen" == *"shuffled"* ]]; then
                mpv --no-video --shuffle ${radio_stations[$chosen]};
        else
                mpv --no-video ${radio_stations[$chosen]};
        fi

elif [[ "$chosen" != "" ]]; then
        notify-send "Searching YouTube is disabled for ytfzf does not work and I wait for alternative..."
        # echo "Starting ytfzf..."
        # ytfzf -D --detach --url-handler-opts='--no-video' $chosen;
        # retVal=$?
        # if [ $retVal -eq 4 ]; then
        #         notify-send "ytfzf (menu-radio): No results scraped"
        # elif [ $retVal -eq 0]; then
        #         pkill mpv;
        # fi
        # exit $retVal

else
        echo "Program terminated" && exit 1
fi
