#!/bin/bash

declare -a options=(
        "Brave"
        "Qutebrowser"
)

chosen=$(printf '%s\n' "${options[@]}" | menu -i -l 20 -p "Browser:")

if [ "$chosen" == "Brave" ]; then
        brave $@
elif [ "$chosen" == "Qutebrowser" ]; then
        qutebrowser $@
else
        echo "Program terminated" && exit 1
fi
