#!/bin/bash

current_power_profile=`powerprofilesctl get`

declare -a options=(
"performance"
"balanced"
"power-saver"
)

chosen=$(printf '%s\n' "${options[@]}" | menu -i -l 20 -p "Set power profile (current: $current_power_profile):")

if [ "$chosen" ]; then
        powerprofilesctl set $chosen
else
        echo "Program terminated" && exit 1
fi
