#!/bin/bash

mac_address=`bluetoothctl devices | grep "Soundcore" | cut -f2 -d" "`

if [ -z $mac_address ] ; then
    echo "No Soundcore device found";
    exit 1
fi

card="bluez_card.${mac_address}"
input="bluez_input.${mac_address}.headset-head-unit"

connect() {
    bluetoothctl connect $mac_address;
}

disconnect() {
    bluetoothctl disconnect $mac_address;
}

reconnect() {
    bluetoothctl disconnect $mac_address && bluetoothctl connect $mac_address;
}

set_profile_a2dp_ldac() {
    echo $card
    pactl set-card-profile $card a2dp_sink
    pactl send-message /card/${card}/bluez switch-codec '"ldac_sq"'
}

set_profile_hhu_msbc() {
    pactl set-card-profile $card handsfree_head_unit
    pactl set-default-source bluez_source.${mac_address}.handsfree_head_unit
}

help() {
    echo "Possible options: connect (c), disconnect (d), reconnect (r), a2dp-ldac (ldac), hhu-msbc (msbc)"
}

case "$1" in
    "c") connect;;
    "connect") connect;;
    "d") disconnect;;
    "disconnect") disconnect;;
    "r") reconnect;;
    "reconnect") reconnect;;
    "ldac") set_profile_a2dp_ldac;;
    "a2dp-ldac") set_profile_a2dp_ldac;;
    "msbc") set_profile_hhu_msbc;;
    "hhu-msbc") set_profile_hhu_msbc;;
    "--help") help;;
esac
